### ISSUE TITLE
Please add support for version 1.21.8

### ISSUE THREAD

**Issue by Ultim4t** [JNNGL/VanillaMinimaps#36]
Finalize the plugin and make it paid with subsequent stable updates. I am ready to purchase it.

Add ItemsAdder support and clear instructions on how to set up the WIKI. This is a really awesome plugin. There are no alternatives.

**Comment by Ultim4t** [comment]
[09:49:42 ERROR]: Error occurred while enabling VanillaMinimaps v1.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R1/CraftServer
        at vanillaminimaps-1.0.1.jar/com.jnngl.vanillaminimaps.command.NMSCommandDispatcherAccessor.vanillaDispatcher(NMSCommandDispatcherAccessor.java:28) ~[vanillaminimaps-1.0.1.jar:?]
        at vanillaminimaps-1.0.1.jar/com.jnngl.vanillaminimaps.VanillaMinimaps.onEnable(VanillaMinimaps.java:144) ~[vanillaminimaps-1.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280) ~[purpur-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:667) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:622) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:744) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:489) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1176) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:311) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R1.CraftServer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[purpur-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[purpur-api-1.21.5-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
        ... 14 more

**Comment by Ultim4t** [comment]
Purpur 1.21.8

**Comment by wilburforce83** [comment]
> Purpur 1.21.8



> [09:49:42 ERROR]: Error occurred while enabling VanillaMinimaps v1.0.1 (Is it up to date?) java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R1/CraftServer at vanillaminimaps-1.0.1.jar/com.jnngl.vanillaminimaps.command.NMSCommandDispatcherAccessor.vanillaDispatcher(NMSCommandDispatcherAccessor.java:28) ~[vanillaminimaps-1.0.1.jar:?] at vanillaminimaps-1.0.1.jar/com.jnngl.vanillaminimaps.VanillaMinimaps.onEnable(VanillaMinimaps.java:144) ~[vanillaminimaps-1.0.1.jar:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:280) ~[purpur-api-1.21.5-R0.1-SNAPSHOT.jar:?] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[purpur-api-1.21.5-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:667) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55] at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:622) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:744) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:489) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1176) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55] at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:311) ~[purpur-1.21.5.jar:1.21.5-2450-61d7f55] at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?] Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R1.CraftServer at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[purpur-api-1.21.5-R0.1-SNAPSHOT.jar:?] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[purpur-api-1.21.5-R0.1-SNAPSHOT.jar:?] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?] ... 14 more

I don't know if you are still looking for this to work, but I am guessing it's dead. I have forked the repo and updated it to work on 1.21.10 + and added some quality of life features; the choice of square mini map, and player head tracking of other players on the server. its here: [https://github.com/wilburforce83/VanillaMinimaps-Next/releases/tag/v1.1.0](https://github.com/wilburforce83/VanillaMinimaps-Next/releases/tag/v1.1.0 )

**Comment by Ultim4t** [comment]
It doesn't work on 1.21.8

[03:58:44 WARN]: [VanillaMinimaps] Task #127 for VanillaMinimaps v1.1.0-mc1.21.10 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/level/ServerEntity$Synchronizer
        at vanillaminimaps-1.1.0-mc1.21.10.jar/com.jnngl.vanillaminimaps.clientside.impl.NMSMinimapPacketSender.spawnItemFrame(NMSMinimapPacketSender.java:58) ~[vanillaminimaps-1.1.0-mc1.21.10.jar:?]
        at vanillaminimaps-1.1.0-mc1.21.10.jar/com.jnngl.vanillaminimaps.clientside.impl.NMSMinimapPacketSender.spawnItemFrame(NMSMinimapPacketSender.java:66) ~[vanillaminimaps-1.1.0-mc1.21.10.jar:?]
        at vanillaminimaps-1.1.0-mc1.21.10.jar/com.jnngl.vanillaminimaps.clientside.impl.NMSMinimapPacketSender.spawnLayer(NMSMinimapPacketSender.java:85) ~[vanillaminimaps-1.1.0-mc1.21.10.jar:?]
        at vanillaminimaps-1.1.0-mc1.21.10.jar/com.jnngl.vanillaminimaps.clientside.AbstractMinimapPacketSender.spawnMinimap(AbstractMinimapPacketSender.java:27) ~[vanillaminimaps-1.1.0-mc1.21.10.jar:?]
        at vanillaminimaps-1.1.0-mc1.21.10.jar/com.jnngl.vanillaminimaps.listener.MinimapListener.enableMinimap(MinimapListener.java:104) ~[vanillaminimaps-1.1.0-mc1.21.10.jar:?]
        at vanillaminimaps-1.1.0-mc1.21.10.jar/com.jnngl.vanillaminimaps.storage.MinimapPlayerDatabase.restore(MinimapPlayerDatabase.java:85) ~[vanillaminimaps-1.1.0-mc1.21.10.jar:?]
        at vanillaminimaps-1.1.0-mc1.21.10.jar/com.jnngl.vanillaminimaps.listener.MinimapListener.lambda$onJoin$0(MinimapListener.java:76) ~[vanillaminimaps-1.1.0-mc1.21.10.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[purpur-1.21.8.jar:1.21.8-2497-a49cdb9]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[purpur-1.21.8.jar:1.21.8-2497-a49cdb9]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[purpur-1.21.8.jar:1.21.8-2497-a49cdb9]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1567) ~[purpur-1.21.8.jar:1.21.8-2497-a49cdb9]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1283) ~[purpur-1.21.8.jar:1.21.8-2497-a49cdb9]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313) ~[purpur-1.21.8.jar:1.21.8-2497-a49cdb9]
        at java.base/java.lang.Thread.run(Thread.java:1474) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.level.ServerEntity$Synchronizer
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:205) ~[purpur-api-1.21.8-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:172) ~[purpur-api-1.21.8-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490) ~[?:?]
        ... 14 more

**Comment by Ultim4t** [comment]
[04:00:08 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/level/ServerEntity$Synchronizer
[04:00:08 WARN]:        at vanillaminimaps-1.1.0-mc1.21.10.jar//com.jnngl.vanillaminimaps.clientside.impl.NMSMinimapPacketSender.spawnItemFrame(NMSMinimapPacketSender.java:58)
[04:00:08 WARN]:        at vanillaminimaps-1.1.0-mc1.21.10.jar//com.jnngl.vanillaminimaps.clientside.impl.NMSMinimapPacketSender.spawnItemFrame(NMSMinimapPacketSender.java:66)
[04:00:08 WARN]:        at vanillaminimaps-1.1.0-mc1.21.10.jar//com.jnngl.vanillaminimaps.clientside.impl.NMSMinimapPacketSender.spawnLayer(NMSMinimapPacketSender.java:85)
[04:00:08 WARN]:        at vanillaminimaps-1.1.0-mc1.21.10.jar//com.jnngl.vanillaminimaps.clientside.AbstractMinimapPacketSender.spawnMinimap(AbstractMinimapPacketSender.java:27)
[04:00:08 WARN]:        at vanillaminimaps-1.1.0-mc1.21.10.jar//com.jnngl.vanillaminimaps.listener.MinimapListener.enableMinimap(MinimapListener.java:104)
[04:00:08 WARN]:        at vanillaminimaps-1.1.0-mc1.21.10.jar//com.jnngl.vanillaminimaps.storage.MinimapPlayerDatabase.restore(MinimapPlayerDatabase.java:85)
[04:00:08 WARN]:        at vanillaminimaps-1.1.0-mc1.21.10.jar//com.jnngl.vanillaminimaps.command.MinimapCommand.enable(MinimapCommand.java:141)
[04:00:08 WARN]:        at vanillaminimaps-1.1.0-mc1.21.10.jar//com.jnngl.vanillaminimaps.command.MinimapCommand.lambda$register$1(MinimapCommand.java:72)
[04:00:08 WARN]:        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[04:00:08 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30)
[04:00:08 WARN]:        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[04:00:08 WARN]:        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[04:00:08 WARN]:        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5)
[04:00:08 WARN]:        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:105)
[04:00:08 WARN]:        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:465)
[04:00:08 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:371)
[04:00:08 WARN]:        at net.minecraft.commands.Commands.performCommand(Commands.java:359)
[04:00:08 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2394)
[04:00:08 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2367)
[04:00:08 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[04:00:08 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155)
[04:00:08 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[04:00:08 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1486)
[04:00:08 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176)
[04:00:08 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129)
[04:00:08 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1466)
[04:00:08 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1460)
[04:00:08 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139)
[04:00:08 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1417)
[04:00:08 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1425)
[04:00:08 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302)
[04:00:08 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:313)
[04:00:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1474)
[04:00:08 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.level.ServerEntity$Synchronizer
[04:00:08 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:205)
[04:00:08 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:172)
[04:00:08 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
[04:00:08 WARN]:        ... 33 more

**Comment by Ultim4t** [comment]
Not all plugins have been updated for version 1.21.10 yet

I still have no idea how to use it, as long as 1.21.8 is more stable.

**Comment by wilburforce83** [comment]
> Not all plugins have been updated for version 1.21.10 yet
> 
> I still have no idea how to use it, as long as 1.21.8 is more stable.

Correct, this is compiled for 1.21.10 and won't load below that. If you move over to my repo page and submit an issue (I don't want to spam JNNGL's repo, especially if the they're not actively maintaining anymore, the emails are super annoying haha), I'll add 1.21.8 to the releases when I get a second.

**Comment by Ultim4t** [comment]
<img width="992" height="719" alt="Image" src="https://github.com/user-attachments/assets/78c51cfc-4d51-4f68-b739-bb47f572918e" />

Does it give an error, am I doing something wrong?

Once again, I apologize for the trouble and spam in the JNNGL topic

**Comment by wilburforce83** [comment]
> <img width="992" height="719" alt="Image" src="https://github.com/user-attachments/assets/78c51cfc-4d51-4f68-b739-bb47f572918e" />
> 
> Does it give an error, am I doing something wrong?
> 
> Once again, I apologize for the trouble and spam in the JNNGL topic
> 

Apologies, I hadn't turned on issue tracking. Should be on now, I've added a few issues including support for 1.21.8 👍
